新增体力推送
baiqwerdvd/StarRailUID pull request #33
Opened 2024-09-06 13:12 UTC by mengluo04

应该没什么奇怪的bug

2024-09-06 13:17 UTC, baiqwerdvd requested changes

2024-09-06 13:17 UTC, baiqwerdvd commented on StarRailUID/utils/database/model.py
> +class srpushadmin(GsAdminModel):
符合一下 class 的命名规范喽，`SrPushAdmin`

2024-09-06 13:21 UTC, baiqwerdvd approved these changes

2024-09-06 13:21 UTC, baiqwerdvd commented on StarRailUID/starrailuid_stamina/notice.py
> +                raw_data = await mys_api.get_daily_data(user.sr_uid)
这里这样是对的吗，我记得我是改成get_sr_daily_data了的

2024-09-06 13:33 UTC, mengluo04 commented on StarRailUID/starrailuid_stamina/notice.py
> +                raw_data = await mys_api.get_daily_data(user.sr_uid)
我的问题，我放一晚上再测测能不能正常执行

2024-09-06 14:03 UTC, baiqwerdvd commented on StarRailUID/starrailuid_stamina/notice.py
> +                raw_data = await mys_api.get_daily_data(user.sr_uid)
好

2024-09-07 04:43 UTC, baiqwerdvd commented
应该可以了吧

2024-09-07 04:44 UTC, mengluo04 commented
> 应该可以了吧

改了点发现的问题，测试没问题了

2024-09-07 04:51 UTC, merged